server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: todo
    password: todo
    sql-script-encoding: UTF-8
    initialization-mode: always
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format-sql: true